# Site settings
title: LHSG Inc.
SEOTitle: LHSG | Metaverse & Blockchain
header-img: img/home-bg.jpg
email: contact.lhsg@gmail.com
description: "Everything about Metaverse & BlockChain. Extending your dream with Blockchain at Metaverse."
keyword: "LHSG, Metaverse, Blockchain, AR, VR, Cloud Storage, Big Data"
url: "http://lhsg.co.kr"
baseurl: ""
github_repo: "https://github.com/lhsg/lhsg.github.io"

# Social Media
github_username: lhsg
facebook_username: lhsgfb
twitter_username: LHSG_

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less", "node_modules", "Gruntfile.js", "package.json", "package-lock.json", "README.md", "PLAN.md", "gatsby-config.js", "src"]

# SAS/SCSS
sass:
  style: compressed
  sass_dir: _sass

# Navigation
header_pages:
  - about.md
  - services.md
  - products.md
  - portfolio.md
  - blog/index.html
  - contact.md

# Friends/Partners
friends:
  - title: "LHSG Official"
    href: "http://lhsg.co.kr"

